# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - spacex-capstone-ibm

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Navigate to app directory and set up virtual environment
        run: |
          cd SpaceX_F9_Landing_Prediction/dash/
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          cd SpaceX_F9_Landing_Prediction/dash/
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Package application for deployment
        run: |
          cd SpaceX_F9_Landing_Prediction/dash/
          zip -r release.zip . -x "venv/*" "*.git/*" "__pycache__/*" "*.pytest_cache/*"
          ls -al  # Confirm release.zip is created

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: SpaceX_F9_Landing_Prediction/dash/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          mkdir -p deployment
          unzip release.zip -d deployment
          ls -al deployment  # Debugging to confirm extracted files

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D41BAB7B77A64178B3A857FA0D59D1F9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2315D577D09B4F62AECA52F48CAE8E2C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2A0A72D561D34EFF997A4CC94CFDA423 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'spacex-capstone-ibm'
          slot-name: 'production'
          package: deployment

