repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        name: Strip Jupyter notebook outputs
        files: \.ipynb$
        args: ["--keep-count"]

